//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyaltyServiceWorker.HistoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoyaltyServiceWorker.HistoryService.BaseExecutionResultOfHistoryh3e0gNRf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoyaltyServiceWorker.HistoryService.HistoryResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfHistoryh3e0gNRf", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoyaltyServiceWorker.HistoryService.HistoryResult))]
    public partial class BaseExecutionResultOfHistoryh3e0gNRf : RoyaltyServiceWorker.HistoryService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoyaltyServiceWorker.HistoryService.History ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoyaltyServiceWorker.HistoryService.History Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryResult", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Services.History")]
    [System.SerializableAttribute()]
    public partial class HistoryResult : RoyaltyServiceWorker.HistoryService.BaseExecutionResultOfHistoryh3e0gNRf {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoyaltyServiceWorker.HistoryService.HistoryUpdatePart AddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoyaltyServiceWorker.HistoryService.HistoryUpdatePart ChangeField;
        
        private long EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoyaltyServiceWorker.HistoryService.HistoryRemovePart RemoveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoyaltyServiceWorker.HistoryService.HistoryUpdatePart Add {
            get {
                return this.AddField;
            }
            set {
                if ((object.ReferenceEquals(this.AddField, value) != true)) {
                    this.AddField = value;
                    this.RaisePropertyChanged("Add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoyaltyServiceWorker.HistoryService.HistoryUpdatePart Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeField, value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoyaltyServiceWorker.HistoryService.HistoryRemovePart Remove {
            get {
                return this.RemoveField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoveField, value) != true)) {
                    this.RemoveField = value;
                    this.RaisePropertyChanged("Remove");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryUpdatePart", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class HistoryUpdatePart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.Account> AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountDataRecordAdditionalColumn> AccountDataRecordAdditionalColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountPhoneMark> AccountPhoneMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSeriesOfNumbersRecord> AccountSeriesOfNumbersRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettings> AccountSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsColumn> AccountSettingsColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsExportDirectory> AccountSettingsExportDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsImportDirectory> AccountSettingsImportDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsSheduleTime> AccountSettingsSheduleTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecord> ImportQueueRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileAccountDataRecord> ImportQueueRecordFileAccountDataRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfo> ImportQueueRecordFileInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfoFile> ImportQueueRecordFileInfoFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.Account> Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountDataRecordAdditionalColumn> AccountDataRecordAdditionalColumn {
            get {
                return this.AccountDataRecordAdditionalColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountDataRecordAdditionalColumnField, value) != true)) {
                    this.AccountDataRecordAdditionalColumnField = value;
                    this.RaisePropertyChanged("AccountDataRecordAdditionalColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountPhoneMark> AccountPhoneMark {
            get {
                return this.AccountPhoneMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPhoneMarkField, value) != true)) {
                    this.AccountPhoneMarkField = value;
                    this.RaisePropertyChanged("AccountPhoneMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSeriesOfNumbersRecord> AccountSeriesOfNumbersRecord {
            get {
                return this.AccountSeriesOfNumbersRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSeriesOfNumbersRecordField, value) != true)) {
                    this.AccountSeriesOfNumbersRecordField = value;
                    this.RaisePropertyChanged("AccountSeriesOfNumbersRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettings> AccountSettings {
            get {
                return this.AccountSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsField, value) != true)) {
                    this.AccountSettingsField = value;
                    this.RaisePropertyChanged("AccountSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsColumn> AccountSettingsColumn {
            get {
                return this.AccountSettingsColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsColumnField, value) != true)) {
                    this.AccountSettingsColumnField = value;
                    this.RaisePropertyChanged("AccountSettingsColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsExportDirectory> AccountSettingsExportDirectory {
            get {
                return this.AccountSettingsExportDirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsExportDirectoryField, value) != true)) {
                    this.AccountSettingsExportDirectoryField = value;
                    this.RaisePropertyChanged("AccountSettingsExportDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsImportDirectory> AccountSettingsImportDirectory {
            get {
                return this.AccountSettingsImportDirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsImportDirectoryField, value) != true)) {
                    this.AccountSettingsImportDirectoryField = value;
                    this.RaisePropertyChanged("AccountSettingsImportDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsSheduleTime> AccountSettingsSheduleTime {
            get {
                return this.AccountSettingsSheduleTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsSheduleTimeField, value) != true)) {
                    this.AccountSettingsSheduleTimeField = value;
                    this.RaisePropertyChanged("AccountSettingsSheduleTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecord> ImportQueueRecord {
            get {
                return this.ImportQueueRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordField, value) != true)) {
                    this.ImportQueueRecordField = value;
                    this.RaisePropertyChanged("ImportQueueRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileAccountDataRecord> ImportQueueRecordFileAccountDataRecord {
            get {
                return this.ImportQueueRecordFileAccountDataRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileAccountDataRecordField, value) != true)) {
                    this.ImportQueueRecordFileAccountDataRecordField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileAccountDataRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfo> ImportQueueRecordFileInfo {
            get {
                return this.ImportQueueRecordFileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileInfoField, value) != true)) {
                    this.ImportQueueRecordFileInfoField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfoFile> ImportQueueRecordFileInfoFile {
            get {
                return this.ImportQueueRecordFileInfoFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileInfoFileField, value) != true)) {
                    this.ImportQueueRecordFileInfoFileField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileInfoFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRemovePart", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class HistoryRemovePart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountDataRecordAdditionalColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountPhoneMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountSeriesOfNumbersRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> AccountSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountSettingsColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountSettingsExportDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountSettingsImportDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> AccountSettingsSheduleTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> ImportQueueRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<long> ImportQueueRecordFileAccountDataRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> ImportQueueRecordFileInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<System.Guid> ImportQueueRecordFileInfoFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountDataRecordAdditionalColumn {
            get {
                return this.AccountDataRecordAdditionalColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountDataRecordAdditionalColumnField, value) != true)) {
                    this.AccountDataRecordAdditionalColumnField = value;
                    this.RaisePropertyChanged("AccountDataRecordAdditionalColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountPhoneMark {
            get {
                return this.AccountPhoneMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPhoneMarkField, value) != true)) {
                    this.AccountPhoneMarkField = value;
                    this.RaisePropertyChanged("AccountPhoneMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountSeriesOfNumbersRecord {
            get {
                return this.AccountSeriesOfNumbersRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSeriesOfNumbersRecordField, value) != true)) {
                    this.AccountSeriesOfNumbersRecordField = value;
                    this.RaisePropertyChanged("AccountSeriesOfNumbersRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> AccountSettings {
            get {
                return this.AccountSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsField, value) != true)) {
                    this.AccountSettingsField = value;
                    this.RaisePropertyChanged("AccountSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountSettingsColumn {
            get {
                return this.AccountSettingsColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsColumnField, value) != true)) {
                    this.AccountSettingsColumnField = value;
                    this.RaisePropertyChanged("AccountSettingsColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountSettingsExportDirectory {
            get {
                return this.AccountSettingsExportDirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsExportDirectoryField, value) != true)) {
                    this.AccountSettingsExportDirectoryField = value;
                    this.RaisePropertyChanged("AccountSettingsExportDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountSettingsImportDirectory {
            get {
                return this.AccountSettingsImportDirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsImportDirectoryField, value) != true)) {
                    this.AccountSettingsImportDirectoryField = value;
                    this.RaisePropertyChanged("AccountSettingsImportDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> AccountSettingsSheduleTime {
            get {
                return this.AccountSettingsSheduleTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountSettingsSheduleTimeField, value) != true)) {
                    this.AccountSettingsSheduleTimeField = value;
                    this.RaisePropertyChanged("AccountSettingsSheduleTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> ImportQueueRecord {
            get {
                return this.ImportQueueRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordField, value) != true)) {
                    this.ImportQueueRecordField = value;
                    this.RaisePropertyChanged("ImportQueueRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<long> ImportQueueRecordFileAccountDataRecord {
            get {
                return this.ImportQueueRecordFileAccountDataRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileAccountDataRecordField, value) != true)) {
                    this.ImportQueueRecordFileAccountDataRecordField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileAccountDataRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> ImportQueueRecordFileInfo {
            get {
                return this.ImportQueueRecordFileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileInfoField, value) != true)) {
                    this.ImportQueueRecordFileInfoField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> ImportQueueRecordFileInfoFile {
            get {
                return this.ImportQueueRecordFileInfoFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportQueueRecordFileInfoFileField, value) != true)) {
                    this.ImportQueueRecordFileInfoFileField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileInfoFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBusyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHiddenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoyaltyServiceWorker.HistoryService.AccountSettings SettingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBusy {
            get {
                return this.IsBusyField;
            }
            set {
                if ((this.IsBusyField.Equals(value) != true)) {
                    this.IsBusyField = value;
                    this.RaisePropertyChanged("IsBusy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHidden {
            get {
                return this.IsHiddenField;
            }
            set {
                if ((this.IsHiddenField.Equals(value) != true)) {
                    this.IsHiddenField = value;
                    this.RaisePropertyChanged("IsHidden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoyaltyServiceWorker.HistoryService.AccountSettings Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDataRecordAdditionalColumn", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountDataRecordAdditionalColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnSystemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnSystemName {
            get {
                return this.ColumnSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnSystemNameField, value) != true)) {
                    this.ColumnSystemNameField = value;
                    this.RaisePropertyChanged("ColumnSystemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Export {
            get {
                return this.ExportField;
            }
            set {
                if ((this.ExportField.Equals(value) != true)) {
                    this.ExportField = value;
                    this.RaisePropertyChanged("Export");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountPhoneMark", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountPhoneMark : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MarkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MarkID {
            get {
                return this.MarkIDField;
            }
            set {
                if ((this.MarkIDField.Equals(value) != true)) {
                    this.MarkIDField = value;
                    this.RaisePropertyChanged("MarkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSeriesOfNumbersRecord", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSeriesOfNumbersRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DelayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DigitCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Delay {
            get {
                return this.DelayField;
            }
            set {
                if ((this.DelayField.Equals(value) != true)) {
                    this.DelayField = value;
                    this.RaisePropertyChanged("Delay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DigitCount {
            get {
                return this.DigitCountField;
            }
            set {
                if ((this.DigitCountField.Equals(value) != true)) {
                    this.DigitCountField = value;
                    this.RaisePropertyChanged("DigitCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSettings", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsColumn> ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsExportDirectory> ExportDirectoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> IgnoreExportTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsImportDirectory> ImportDirectoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsSheduleTime> SheduleTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TimeForTrustField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsColumn> Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsExportDirectory> ExportDirectories {
            get {
                return this.ExportDirectoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportDirectoriesField, value) != true)) {
                    this.ExportDirectoriesField = value;
                    this.RaisePropertyChanged("ExportDirectories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> IgnoreExportTime {
            get {
                return this.IgnoreExportTimeField;
            }
            set {
                if ((this.IgnoreExportTimeField.Equals(value) != true)) {
                    this.IgnoreExportTimeField = value;
                    this.RaisePropertyChanged("IgnoreExportTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsImportDirectory> ImportDirectories {
            get {
                return this.ImportDirectoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDirectoriesField, value) != true)) {
                    this.ImportDirectoriesField = value;
                    this.RaisePropertyChanged("ImportDirectories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.AccountSettingsSheduleTime> SheduleTimes {
            get {
                return this.SheduleTimesField;
            }
            set {
                if ((object.ReferenceEquals(this.SheduleTimesField, value) != true)) {
                    this.SheduleTimesField = value;
                    this.RaisePropertyChanged("SheduleTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeForTrust {
            get {
                return this.TimeForTrustField;
            }
            set {
                if ((this.TimeForTrustField.Equals(value) != true)) {
                    this.TimeForTrustField = value;
                    this.RaisePropertyChanged("TimeForTrust");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSettingsColumn", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSettingsColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ColumnTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ColumnTypeID {
            get {
                return this.ColumnTypeIDField;
            }
            set {
                if ((this.ColumnTypeIDField.Equals(value) != true)) {
                    this.ColumnTypeIDField = value;
                    this.RaisePropertyChanged("ColumnTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSettingsExportDirectory", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSettingsExportDirectory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecuteAfterAnalizeCommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MarkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeoutForExecuteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectoryPath {
            get {
                return this.DirectoryPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryPathField, value) != true)) {
                    this.DirectoryPathField = value;
                    this.RaisePropertyChanged("DirectoryPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncodingName {
            get {
                return this.EncodingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingNameField, value) != true)) {
                    this.EncodingNameField = value;
                    this.RaisePropertyChanged("EncodingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecuteAfterAnalizeCommand {
            get {
                return this.ExecuteAfterAnalizeCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecuteAfterAnalizeCommandField, value) != true)) {
                    this.ExecuteAfterAnalizeCommandField = value;
                    this.RaisePropertyChanged("ExecuteAfterAnalizeCommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MarkID {
            get {
                return this.MarkIDField;
            }
            set {
                if ((this.MarkIDField.Equals(value) != true)) {
                    this.MarkIDField = value;
                    this.RaisePropertyChanged("MarkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeoutForExecute {
            get {
                return this.TimeoutForExecuteField;
            }
            set {
                if ((this.TimeoutForExecuteField.Equals(value) != true)) {
                    this.TimeoutForExecuteField = value;
                    this.RaisePropertyChanged("TimeoutForExecute");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSettingsImportDirectory", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSettingsImportDirectory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeleteFileAfterImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForAnalizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RecursiveFolderSearchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeleteFileAfterImport {
            get {
                return this.DeleteFileAfterImportField;
            }
            set {
                if ((this.DeleteFileAfterImportField.Equals(value) != true)) {
                    this.DeleteFileAfterImportField = value;
                    this.RaisePropertyChanged("DeleteFileAfterImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncodingName {
            get {
                return this.EncodingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingNameField, value) != true)) {
                    this.EncodingNameField = value;
                    this.RaisePropertyChanged("EncodingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForAnalize {
            get {
                return this.ForAnalizeField;
            }
            set {
                if ((this.ForAnalizeField.Equals(value) != true)) {
                    this.ForAnalizeField = value;
                    this.RaisePropertyChanged("ForAnalize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RecursiveFolderSearch {
            get {
                return this.RecursiveFolderSearchField;
            }
            set {
                if ((this.RecursiveFolderSearchField.Equals(value) != true)) {
                    this.RecursiveFolderSearchField = value;
                    this.RaisePropertyChanged("RecursiveFolderSearch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSettingsSheduleTime", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class AccountSettingsSheduleTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportQueueRecord", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class ImportQueueRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfo> FileInfoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProcessedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountUID {
            get {
                return this.AccountUIDField;
            }
            set {
                if ((this.AccountUIDField.Equals(value) != true)) {
                    this.AccountUIDField = value;
                    this.RaisePropertyChanged("AccountUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfo> FileInfoes {
            get {
                return this.FileInfoesField;
            }
            set {
                if ((object.ReferenceEquals(this.FileInfoesField, value) != true)) {
                    this.FileInfoesField = value;
                    this.RaisePropertyChanged("FileInfoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProcessedDate {
            get {
                return this.ProcessedDateField;
            }
            set {
                if ((this.ProcessedDateField.Equals(value) != true)) {
                    this.ProcessedDateField = value;
                    this.RaisePropertyChanged("ProcessedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportQueueRecordFileAccountDataRecord", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class ImportQueueRecordFileAccountDataRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AccountDataRecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImportQueueRecordFileUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LoadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AccountDataRecordID {
            get {
                return this.AccountDataRecordIDField;
            }
            set {
                if ((this.AccountDataRecordIDField.Equals(value) != true)) {
                    this.AccountDataRecordIDField = value;
                    this.RaisePropertyChanged("AccountDataRecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImportQueueRecordFileUID {
            get {
                return this.ImportQueueRecordFileUIDField;
            }
            set {
                if ((this.ImportQueueRecordFileUIDField.Equals(value) != true)) {
                    this.ImportQueueRecordFileUIDField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LoadDate {
            get {
                return this.LoadDateField;
            }
            set {
                if ((this.LoadDateField.Equals(value) != true)) {
                    this.LoadDateField = value;
                    this.RaisePropertyChanged("LoadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportQueueRecordFileInfo", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class ImportQueueRecordFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfoFile> FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForAnalizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ImportQueueRecordStateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImportQueueRecordUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileAccountDataRecord> LoadedRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileInfoFile> Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Finished {
            get {
                return this.FinishedField;
            }
            set {
                if ((this.FinishedField.Equals(value) != true)) {
                    this.FinishedField = value;
                    this.RaisePropertyChanged("Finished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForAnalize {
            get {
                return this.ForAnalizeField;
            }
            set {
                if ((this.ForAnalizeField.Equals(value) != true)) {
                    this.ForAnalizeField = value;
                    this.RaisePropertyChanged("ForAnalize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ImportQueueRecordStateID {
            get {
                return this.ImportQueueRecordStateIDField;
            }
            set {
                if ((this.ImportQueueRecordStateIDField.Equals(value) != true)) {
                    this.ImportQueueRecordStateIDField = value;
                    this.RaisePropertyChanged("ImportQueueRecordStateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImportQueueRecordUID {
            get {
                return this.ImportQueueRecordUIDField;
            }
            set {
                if ((this.ImportQueueRecordUIDField.Equals(value) != true)) {
                    this.ImportQueueRecordUIDField = value;
                    this.RaisePropertyChanged("ImportQueueRecordUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoyaltyServiceWorker.HistoryService.ImportQueueRecordFileAccountDataRecord> LoadedRecords {
            get {
                return this.LoadedRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadedRecordsField, value) != true)) {
                    this.LoadedRecordsField = value;
                    this.RaisePropertyChanged("LoadedRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceFilePath {
            get {
                return this.SourceFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceFilePathField, value) != true)) {
                    this.SourceFilePathField = value;
                    this.RaisePropertyChanged("SourceFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Started {
            get {
                return this.StartedField;
            }
            set {
                if ((this.StartedField.Equals(value) != true)) {
                    this.StartedField = value;
                    this.RaisePropertyChanged("Started");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportQueueRecordFileInfoFile", Namespace="http://schemas.datacontract.org/2004/07/RoyaltyService.Model")]
    [System.SerializableAttribute()]
    public partial class ImportQueueRecordFileInfoFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FileUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImportQueueRecordFileInfoUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeSystemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileUID {
            get {
                return this.FileUIDField;
            }
            set {
                if ((this.FileUIDField.Equals(value) != true)) {
                    this.FileUIDField = value;
                    this.RaisePropertyChanged("FileUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImportQueueRecordFileInfoUID {
            get {
                return this.ImportQueueRecordFileInfoUIDField;
            }
            set {
                if ((this.ImportQueueRecordFileInfoUIDField.Equals(value) != true)) {
                    this.ImportQueueRecordFileInfoUIDField = value;
                    this.RaisePropertyChanged("ImportQueueRecordFileInfoUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeSystemName {
            get {
                return this.TypeSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeSystemNameField, value) != true)) {
                    this.TypeSystemNameField = value;
                    this.RaisePropertyChanged("TypeSystemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.IHistoryServiceREST")]
    public interface IHistoryServiceREST {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGet", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetResponse")]
        RoyaltyServiceWorker.HistoryService.HistoryResult RESTGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGetFrom", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetFromResponse")]
        RoyaltyServiceWorker.HistoryService.HistoryResult RESTGetFrom(string identifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoryServiceRESTChannel : RoyaltyServiceWorker.HistoryService.IHistoryServiceREST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoryServiceRESTClient : System.ServiceModel.ClientBase<RoyaltyServiceWorker.HistoryService.IHistoryServiceREST>, RoyaltyServiceWorker.HistoryService.IHistoryServiceREST {
        
        public HistoryServiceRESTClient() {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceRESTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public RoyaltyServiceWorker.HistoryService.HistoryResult RESTGet() {
            return base.Channel.RESTGet();
        }
        
        public RoyaltyServiceWorker.HistoryService.HistoryResult RESTGetFrom(string identifier) {
            return base.Channel.RESTGetFrom(identifier);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.IHistoryService")]
    public interface IHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Get", ReplyAction="http://tempuri.org/IHistoryService/GetResponse")]
        RoyaltyServiceWorker.HistoryService.HistoryResult Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetFrom", ReplyAction="http://tempuri.org/IHistoryService/GetFromResponse")]
        RoyaltyServiceWorker.HistoryService.HistoryResult GetFrom(long identifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoryServiceChannel : RoyaltyServiceWorker.HistoryService.IHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoryServiceClient : System.ServiceModel.ClientBase<RoyaltyServiceWorker.HistoryService.IHistoryService>, RoyaltyServiceWorker.HistoryService.IHistoryService {
        
        public HistoryServiceClient() {
        }
        
        public HistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public RoyaltyServiceWorker.HistoryService.HistoryResult Get() {
            return base.Channel.Get();
        }
        
        public RoyaltyServiceWorker.HistoryService.HistoryResult GetFrom(long identifier) {
            return base.Channel.GetFrom(identifier);
        }
    }
}
