//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyaltyWorker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoyaltyWorker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one files added in queue record..
        /// </summary>
        public static string ROYALTYWATCHER_NoOneFilesInQueue {
            get {
                return ResourceManager.GetString("ROYALTYWATCHER_NoOneFilesInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher is busy now. Try to check account later..
        /// </summary>
        public static string ROYALTYWATCHER_WatherIsBusyNow {
            get {
                return ResourceManager.GetString("ROYALTYWATCHER_WatherIsBusyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file not found in database..
        /// </summary>
        public static string ROYALTYWORKER_ImportFileNotFound {
            get {
                return ResourceManager.GetString("ROYALTYWORKER_ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker is busy now. Try to check account later..
        /// </summary>
        public static string ROYALTYWORKER_WorkerIsBusyNow {
            get {
                return ResourceManager.GetString("ROYALTYWORKER_WorkerIsBusyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is busy. Stop it before run once..
        /// </summary>
        public static string STARTSTOPBASE_StopBeforeRun {
            get {
                return ResourceManager.GetString("STARTSTOPBASE_StopBeforeRun", resourceCulture);
            }
        }
    }
}
