//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyaltyRepository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoyaltyRepository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default account not found.
        /// </summary>
        public static string _DEFAULT_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("_DEFAULT_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude parameter length must be less or equals 250.
        /// </summary>
        public static string AccountDictionaryExcludeMaxLength {
            get {
                return ResourceManager.GetString("AccountDictionaryExcludeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude parameter can&apos;t be empty.
        /// </summary>
        public static string AccountDictionaryExcludeMinLength {
            get {
                return ResourceManager.GetString("AccountDictionaryExcludeMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude parameter required.
        /// </summary>
        public static string AccountDictionaryExcludeRequired {
            get {
                return ResourceManager.GetString("AccountDictionaryExcludeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name length must be less or equals 250.
        /// </summary>
        public static string AccountNameMaxLength {
            get {
                return ResourceManager.GetString("AccountNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name can&apos;t be empty.
        /// </summary>
        public static string AccountNameRequired {
            get {
                return ResourceManager.GetString("AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name length must be less or equals 100.
        /// </summary>
        public static string CityNameMaxLength {
            get {
                return ResourceManager.GetString("CityNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name can&apos;t be empty.
        /// </summary>
        public static string CityNameMinLength {
            get {
                return ResourceManager.GetString("CityNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name required.
        /// </summary>
        public static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default phone number code length must be less or equals 20.
        /// </summary>
        public static string CityPhoneNumberCodeMaxLength {
            get {
                return ResourceManager.GetString("CityPhoneNumberCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string COLUMNTYPE_ADDRESS {
            get {
                return ResourceManager.GetString("COLUMNTYPE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string COLUMNTYPE_AREA {
            get {
                return ResourceManager.GetString("COLUMNTYPE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string COLUMNTYPE_CITY {
            get {
                return ResourceManager.GetString("COLUMNTYPE_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string COLUMNTYPE_HOST {
            get {
                return ResourceManager.GetString("COLUMNTYPE_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string COLUMNTYPE_MARK {
            get {
                return ResourceManager.GetString("COLUMNTYPE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string COLUMNTYPE_PHONE {
            get {
                return ResourceManager.GetString("COLUMNTYPE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path type system name length must be less or equals 100.
        /// </summary>
        public static string ColumnTypeNameMaxLength {
            get {
                return ResourceManager.GetString("ColumnTypeNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path type system name required.
        /// </summary>
        public static string ColumnTypeNameRequred {
            get {
                return ResourceManager.GetString("ColumnTypeNameRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name can&apos;t be empty.
        /// </summary>
        public static string DataAdditionalColumnNameMaxLength {
            get {
                return ResourceManager.GetString("DataAdditionalColumnNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name length must be less or equals 250.
        /// </summary>
        public static string DataAdditionalColumnNameRequired {
            get {
                return ResourceManager.GetString("DataAdditionalColumnNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System column name can&apos;t be empty.
        /// </summary>
        public static string DataAdditionalColumnSystemNameMaxLength {
            get {
                return ResourceManager.GetString("DataAdditionalColumnSystemNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System column name length must be less or equals 250.
        /// </summary>
        public static string DataAdditionalColumnSystemNameRequired {
            get {
                return ResourceManager.GetString("DataAdditionalColumnSystemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name length must be less or equals 250.
        /// </summary>
        public static string HostNameMaxLength {
            get {
                return ResourceManager.GetString("HostNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name can&apos;t be empty.
        /// </summary>
        public static string HostNameRequred {
            get {
                return ResourceManager.GetString("HostNameRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number length must be less or equals 20.
        /// </summary>
        public static string HouseNumberMaxLength {
            get {
                return ResourceManager.GetString("HouseNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not setted.
        /// </summary>
        public static string MARK_DEFAULT {
            get {
                return ResourceManager.GetString("MARK_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half trusted.
        /// </summary>
        public static string MARK_HALFTRUSTED {
            get {
                return ResourceManager.GetString("MARK_HALFTRUSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not trusted.
        /// </summary>
        public static string MARK_NOTTRUSTED {
            get {
                return ResourceManager.GetString("MARK_NOTTRUSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspicious.
        /// </summary>
        public static string MARK_SUSPICIOUS {
            get {
                return ResourceManager.GetString("MARK_SUSPICIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted.
        /// </summary>
        public static string MARK_TRUSTED {
            get {
                return ResourceManager.GetString("MARK_TRUSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string MARK_UNKNOWN {
            get {
                return ResourceManager.GetString("MARK_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark system name length must be less or equals 100.
        /// </summary>
        public static string MarkNameMaxLength {
            get {
                return ResourceManager.GetString("MarkNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark system name can&apos;t be empty.
        /// </summary>
        public static string MarkNameMinLength {
            get {
                return ResourceManager.GetString("MarkNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark system name required.
        /// </summary>
        public static string MarkNameRequred {
            get {
                return ResourceManager.GetString("MarkNameRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number length must be less or equals 20.
        /// </summary>
        public static string PhoneNumberMaxLength {
            get {
                return ResourceManager.GetString("PhoneNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can&apos;t be empty.
        /// </summary>
        public static string PhoneNumberMinLength {
            get {
                return ResourceManager.GetString("PhoneNumberMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string QUEUERECORDSTATE_ERROR {
            get {
                return ResourceManager.GetString("QUEUERECORDSTATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string QUEUERECORDSTATE_PROCESSED {
            get {
                return ResourceManager.GetString("QUEUERECORDSTATE_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to proceed.
        /// </summary>
        public static string QUEUERECORDSTATE_TRYTOPROCESS {
            get {
                return ResourceManager.GetString("QUEUERECORDSTATE_TRYTOPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        public static string QUEUERECORDSTATE_WAIT {
            get {
                return ResourceManager.GetString("QUEUERECORDSTATE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record state name length must be less or equals 20.
        /// </summary>
        public static string QueueRecordStateNameMaxLength {
            get {
                return ResourceManager.GetString("QueueRecordStateNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record state name required.
        /// </summary>
        public static string QueueRecordStateNameRequred {
            get {
                return ResourceManager.GetString("QueueRecordStateNameRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name length must be less or equals 100.
        /// </summary>
        public static string StreetNameMaxLength {
            get {
                return ResourceManager.GetString("StreetNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name required.
        /// </summary>
        public static string StreetNameRequred {
            get {
                return ResourceManager.GetString("StreetNameRequred", resourceCulture);
            }
        }
    }
}
