// <auto-generated />
namespace RoyaltyRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration_AddTimeoutForExecuteForExportDirectory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_AddTimeoutForExecuteForExportDirectory));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011912436_Migration_AddTimeoutForExecuteForExportDirectory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
