// <auto-generated />
namespace RoyaltyRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration_Account_Settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_Account_Settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201509070439481_Migration_Account_Settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
